### PR TITLE
java: make load test framework work with google-cloud-pubsub 0.20.1

### PR DESCRIPTION
**Pull request by pongad**
The vkt package is removed because it is no longer possible to
publish messages from the autogenerated client.

The version of the experimental client is bumped to 0.2.1-EXPERIMENTAL
for dependency update

### CODE REVIEW

**Comment by pongad** [comment]
The build is failing because `0.2.1-EXPERIMENTAL` is not published. After installing the client, everything works on my computer though.

**Comment by mdietz94** [comment]
Can we publish 0.2.1-EXPERIMENTAL?

**Comment by pongad** [comment]
@mdietz94 I cannot publish it myself since I don't have permission to do so at Maven. What I *can* do is splitting this PR into the experimental client PR and load test framework PR, merge the first, publish, then merge the second so you're never in a bad state. Would you rather I do that?

**Comment by mdietz94** [comment]
Let me get davidtorres@ to push the updated client, then I'll approve this PR.

**Comment by davidtorres** [comment]
Just updated it maven with 0.2.1-EXPERIMENTAL

You can revert your changes to the client/pom.xml file, I already committed these changes

**Comment by pongad** [comment]
Thank you @davidtorres and @mdietz94 , PTAL

**Comment by mdietz94** [comment]
This was missing flow control options, and didn't remove some parts of VTK, I now have it working against 0.22.

**Pull request closed without merging**
