### PR TITLE
Update kafka-connect api to 2.1.0 and add support for ConnectHeaders

### PR DESCRIPTION
**Pull request by cyanezp**
Updating to kafka-api 2.1.0 allows us to use ConnectHeaders and this way match Kafka Headers to PubSub message attributes and vice versa

### CODE REVIEW

**Comment by cyanezp** [comment]
I signed it!

**Comment by kamalaboulhosn** [comment]
Does this do something different from #195?

**Comment by cyanezp** [comment]
Oh... I'm so sorry!
I committed to my repo on March 11 but I totally forgot to create a pull request (newbie mistake). I'll diff the code to see if it's something different, but I think we're looking for the same goal.

**Comment by cyanezp** [comment]
Indeed, there is a difference with #195 because in that PR only supports to copy headers from Kafka to PubSub (CloudPubSubSinkTask), but this PR also allows to copy attributes from PubSub to Kafka (CloudPubSubSourceTask). So, I'll close this PR, update my branch with the latest changes and create a new pull request.

Thanks!

**Pull request closed without merging**
