### PR TITLE
Fix null key and exception about read-only ByteBuffer that happens wh…

### PR DESCRIPTION
**Pull request by kamalaboulhosn**
…en using a JsonConverter in a source connector.

Fixes issue #77.

### CODE REVIEW

**Comment by jare19** [comment]
I tested a build with maven including this PR and it does not complete (I see one check has failed here too) 
```
../cloud-pubsub-kafka/kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java:[65,58] error: incompatible types: Set<Object> cannot be converted to Set<String>
```
thanks for the work on this!

**Comment by kamalaboulhosn** [comment]
Did you switch to the kafka-connector-work branch? That branch was behind some changes on master that are required when using Java 7. I have now rebased that branch and it should build with Java 7. Master with adding this change should work regardless.

**Comment by jare19** [comment]
Yep, I did move your changes to master and tried from there..., I will try a fresh go at it, I probably screwed something up. THANKS!

**Comment by jare19** [comment]
environment error on my end, this PR fixes the issue #78

**Pull request merged**
