### PR TITLE
Add PubSubTemporaryTopic class

### PR DESCRIPTION
**Pull request by XiaoYang-Code4Fun**
#76

### CODE REVIEW

**Comment by kamalaboulhosn** [comment]
I have no familiarity with the JMS work. Would it be better to have someone working on that project review this?

**Comment by kir-titievsky** [comment]
Redirecting review to the JMS team.

**Comment by kir-titievsky** [comment]
@XiaoYang-Code4Fun This pull request seems to be stuck because you haven't accepted the contributor license agreement.  You may also need to update to most recent master, but that does not seem to be blocking.

**Comment by XiaoYang-Code4Fun** [comment]
@kir-titievsky That's strange. The other day I also had a pull request that failed CLA check, but that was because I didn't use my cooperate email. All Googlers should already be covered by the cooperate CLA. After I switched to my cooperate email, I was able to merge that pull request. This one is stuck in the waiting CLA report stage. Not sure what's going on here.

**Comment by urshunkeler** [comment]
I see the CLA as passed ("cla/google — All necessary CLAs are signed").
Where do you see a problem?

On Fri, Apr 7, 2017 at 10:57 AM, Xiao (Frank) Yang <notifications@github.com

**Pull request merged**
