### PR TITLE
Resolve dependency issue

### PR DESCRIPTION
**Pull request by jinankjain**
Resolve this issue

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:221)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:198)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:159)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:68)
```

### CODE REVIEW

**Comment by jinankjain** [comment]
I signed it!

**Comment by kamalaboulhosn** [comment]
I'm a little surprised this is necessary. I don't think the connector refers to anything in Guava that isn't already pulled in with the dependency on com.google.apis (which is used for ListenableFuture as it is part of the API used to make Pull calls). Do you have steps to reproduce this issue?

**Comment by jinankjain** [comment]
@kamalaboulhosn 

Steps to reproduce:

I ran these commands ./bin/connect-distributed.sh config/connect-distributed.properties /kafka-connector/config/cps-sink-connector.properties. CLASSPATH was set properly to the jar generated by mvn package.

**Comment by kamalaboulhosn** [comment]
@jinankjain Which version of Kafka were you running and on which platform?

**Comment by jinankjain** [comment]
@kamalaboulhosn `kafka_2.12-0.11.0.0`

**Comment by kamalaboulhosn** [comment]
Thank you for pointing this issue out. I think PR #117 is a little bit better approach. Ultimately, the issue is that some of the connector's dependencies pull in an older version of guava. Rather than add an explicit dependency to the connector that it ultimately doesn't use, I think it's better just to exclude guava from the built package.

**Comment by jinankjain** [comment]
Agreed 👍

**Pull request closed without merging**
