### PR TITLE
update gcloud Tasks with high perf client

### PR DESCRIPTION
**Pull request by pongad**
I verified that tests are working. However, we should not submit this, until `google-cloud-pubsub` publishes `0.9.3-alpha` (without the SNAPSHOT). Otherwise all builds will fail.

### CODE REVIEW

**Comment by pongad** [comment]
This should be working now

**Comment by mdietz94** [comment]
Just to confirm, is this safe for me to merge?

**Comment by pongad** [comment]
@mdietz94 I think so, maybe wait for Travis to make sure?

**Comment by mdietz94** [comment]
Travis tests are broken, they were written by a former intern and are
unreliable. If you've run this code through the framework and it's worked
that's fine, the code LGTM

**Comment by pongad** [comment]
@mdietz94 Ah I see. The code does work when I tried it. Though Travis is failing, it also verified that the new package is up and compiling. (It fails while testing but compiled OK).  I think we should be good.

**Pull request merged**
